logging:
  level: INFO
  loggers:
    'org.dropwizard.copycat.example': DEBUG
  appenders:
    - type: 'console'

server:
  applicationConnectors:
  - type: http
    port: 8280
  adminConnectors:
  - type: http
    port: 8281

copycat:
  address:
    host: localhost
    port: 9200
  members:
    - host: localhost
      port: 9100
    - host: localhost
      port: 9200
    - host: localhost
      port: 9300
  log: logs/node2
